loja/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls, name= 'admin'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views

app_name ='pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe')
]

pedido/models.py
from django.db import models
from django.contrib.auth.models import User

class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default='C',
        max_length = 1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', ' Finalizado'),
        )
    )

    def __str__(self):
        return f'Pedido n° {self.pk}'

class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField()
    quantidade = models.IntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'
    
    class Meta:
        verbose_name = 'Item do Pedido'
        verbose_name_plural = 'Itens do pedido'

pedido/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from .models import Pedido, ItemPedido

from produto.models import Variacao
from utils import utils

#Criando uma classe para verificar se o usuário está criado para acessar uma outra classe
class DispatchRequiredLoginMixin(View):
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        return super().dispatch(request, *args, **kwargs)
    #Criando um método para fazer com que só apareça os pedidos do usuário que realizou eles

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(usuario=self.request.user)
        return qs
class Pagar(DispatchRequiredLoginMixin, DetailView):
        template_name = 'pedido/pagar.html'
        model = Pedido
        pk_url_kwarg = 'pk'
        context_object_name = 'pedido'


        

class SalvarPedido(View):
    template_name = 'pedido/pagar.html'

    def get(self, *args, **kwargs):
        #checagem se o usuário não está logado
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer o Login.'
            )
            return redirect ('perfil:criar')

        #Checando se o carrinho possui algum produtod
        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'O carrinho está vazio!'
            )
            return redirect ('produto:lista')
        #checando se a quantidade de variacoes do produto do carrinho ainda tem em estoque
        carrinho = self.request.session.get('carrinho')
        carrinho_variacao_ids = [v for v in carrinho]

        #Selecionando os produtos do carrinho para poder manipular
        #passando o .selecte_related('Produto') para diminuir a requisição no SQL
        bd_variacoes = list (Variacao.objects.select_related('Produto').filter(id__in=carrinho_variacao_ids))
        

        for variacao in bd_variacoes:
            vid = str(variacao.id)
            estoque = variacao.estoque
            qtd_carrinho = carrinho[vid]['quantidade']
            preco_unit = carrinho[vid]['preco_unitario']
            preco_unit_promocional = carrinho[vid]['preco_unitario_promocional']

            error_msg_estoque = ''

            if estoque < qtd_carrinho:
                carrinho[vid]['quantidade'] = estoque
                carrinho[vid]['preco_quantitativo'] = estoque * preco_unit
                carrinho[vid]['preco_quantitativo_promocional'] = estoque * preco_unit_promocional

                error_msg_estoque ='Estoque insuficiente para alguns produtos do seu carrinho. Reduzimos a quantidade desses produtos. Por favor, verifique novamente o seu carrinho antes de confirmar a compra.'

            if error_msg_estoque:
                messages.error(
                    self.request,
                    error_msg_estoque
                )
                self.request.session.save()
                return redirect('produto:carrinho')
        qtd_total_carrinho = utils.cart_total_qtd(carrinho)    
        valor_total_carrinho = utils.cart_totals(carrinho)  
        #Registrando o pedido
        pedido = Pedido(
            usuario=self.request.user,
            total = valor_total_carrinho,
            qtd_total = qtd_total_carrinho,
            status='C',
        ) 

        pedido.save()

        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promocional=v['preco_quantitativo_promocional'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )
        contexto = {

        }
        
        del self.request.session['carrinho']
        return redirect(
            reverse(
                'pedido:pagar',
                kwargs = {
                    'pk': pedido.pk
                }
            )
        )
        # return render(self.request, self.template_name, contexto)
class Detalhe(DispatchRequiredLoginMixin, DetailView):
    model = Pedido
    context_object_name = 'pedido'
    template_name = 'pedido/detalhe.html'
    pk_url_kwarg = 'pk'
    
class Lista(DispatchRequiredLoginMixin, ListView):
    model = Pedido
    context_object_name = 'pedidos'
    template_name = 'pedido/lista.html'
    paginate_by = 5
    ordering = ['-id']

pedido/templates/pedido/detalhe.html
{% extends "base.html" %}
{% load omfilters %}
{% load static %}
{% block titulo %}Detalhe | {{pedido}} - {% endblock titulo %}


{% block conteudo %}

    {% include "partials/_pedido.html" %}

{% endblock conteudo %}

pedido/templates/pedido/lista.html
{% extends "base.html" %}
{% load omfilters %}
{% block titulo %}Pedidos Realizados | {% endblock titulo %}


{% block conteudo %}

<div class="row">
    <div class="col">
        <h3 class="mb-4">Pedidos de {{user}}</h3>
        <p>Abaixo todos os seus pedidos realizados na loja.</p>

        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th scope="col">Pedido</th>
                    <th scope="col">Total</th>
                    <th scope="col">Qtd. Itens</th>
                    <th scope="col">Status</th>
                    <th scope="col">Mais detalhes</th>
                </tr>

                {% for pedido in pedidos %}
                    <tr>
                        <th scope="row">{{pedido}}</td>
                        <td>{{pedido.total|formata_preco}}</td>
                        <td>{{pedido.qtd_total}}</td>
                        <td>{{pedido.get_status_display}}</td>
                        <td>
                            <a href="{% url "pedido:detalhe" pedido.id %}">
                                Ver <i class="fas fa-search-plus ml-2"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}


            </table>
        </div>
    </div>
</div>

{% include "partials/_pagination.html" %}

{% endblock conteudo %}

pedido/templates/pedido/pagar.html
{% extends "base.html" %}
{% load omfilters %}
{% load static %}
{% block titulo %}Pagamento | {% endblock titulo %}


{% block conteudo %}
    <div class="col">
        <h3 class="text-center">Pagamento com Cartão de Crédito</h3>
        <div class="checkout">
            <div class="credit-card-box">
            <div class="flip">
                <div class="front">
                <div class="chip"></div>
                <div class="logo">
                    <svg version="1.1" id="visa" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                        width="47.834px" height="47.834px" viewBox="0 0 47.834 47.834" style="enable-background:new 0 0 47.834 47.834;">
                    <g>
                        <g>
                        <path d="M44.688,16.814h-3.004c-0.933,0-1.627,0.254-2.037,1.184l-5.773,13.074h4.083c0,0,0.666-1.758,0.817-2.143
                                c0.447,0,4.414,0.006,4.979,0.006c0.116,0.498,0.474,2.137,0.474,2.137h3.607L44.688,16.814z M39.893,26.01
                                c0.32-0.819,1.549-3.987,1.549-3.987c-0.021,0.039,0.317-0.825,0.518-1.362l0.262,1.23c0,0,0.745,3.406,0.901,4.119H39.893z
                                M34.146,26.404c-0.028,2.963-2.684,4.875-6.771,4.875c-1.743-0.018-3.422-0.361-4.332-0.76l0.547-3.193l0.501,0.228
                                c1.277,0.532,2.104,0.747,3.661,0.747c1.117,0,2.313-0.438,2.325-1.393c0.007-0.625-0.501-1.07-2.016-1.77
                                c-1.476-0.683-3.43-1.827-3.405-3.876c0.021-2.773,2.729-4.708,6.571-4.708c1.506,0,2.713,0.31,3.483,0.599l-0.526,3.092
                                l-0.351-0.165c-0.716-0.288-1.638-0.566-2.91-0.546c-1.522,0-2.228,0.634-2.228,1.227c-0.008,0.668,0.824,1.108,2.184,1.77
                                C33.126,23.546,34.163,24.783,34.146,26.404z M0,16.962l0.05-0.286h6.028c0.813,0.031,1.468,0.29,1.694,1.159l1.311,6.304
                                C7.795,20.842,4.691,18.099,0,16.962z M17.581,16.812l-6.123,14.239l-4.114,0.007L3.862,19.161
                                c2.503,1.602,4.635,4.144,5.386,5.914l0.406,1.469l3.808-9.729L17.581,16.812L17.581,16.812z M19.153,16.8h3.89L20.61,31.066
                                h-3.888L19.153,16.8z"/>
                        </g>
                    </g>
                    </svg>
                </div>
                <div class="number"></div>
                <div class="card-holder">
                    <label>Nome do Titular</label>
                    <div></div>
                </div>
                <div class="card-expiration-date">
                    <label>Data de Expriação</label>
                    <div></div>
                </div>
                </div>
                <div class="back">
                <div class="strip"></div>
                <div class="logo">
                    <svg version="1.1" id="visa" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                        width="47.834px" height="47.834px" viewBox="0 0 47.834 47.834" style="enable-background:new 0 0 47.834 47.834;">
                    <g>
                        <g>
                        <path d="M44.688,16.814h-3.004c-0.933,0-1.627,0.254-2.037,1.184l-5.773,13.074h4.083c0,0,0.666-1.758,0.817-2.143
                                c0.447,0,4.414,0.006,4.979,0.006c0.116,0.498,0.474,2.137,0.474,2.137h3.607L44.688,16.814z M39.893,26.01
                                c0.32-0.819,1.549-3.987,1.549-3.987c-0.021,0.039,0.317-0.825,0.518-1.362l0.262,1.23c0,0,0.745,3.406,0.901,4.119H39.893z
                                M34.146,26.404c-0.028,2.963-2.684,4.875-6.771,4.875c-1.743-0.018-3.422-0.361-4.332-0.76l0.547-3.193l0.501,0.228
                                c1.277,0.532,2.104,0.747,3.661,0.747c1.117,0,2.313-0.438,2.325-1.393c0.007-0.625-0.501-1.07-2.016-1.77
                                c-1.476-0.683-3.43-1.827-3.405-3.876c0.021-2.773,2.729-4.708,6.571-4.708c1.506,0,2.713,0.31,3.483,0.599l-0.526,3.092
                                l-0.351-0.165c-0.716-0.288-1.638-0.566-2.91-0.546c-1.522,0-2.228,0.634-2.228,1.227c-0.008,0.668,0.824,1.108,2.184,1.77
                                C33.126,23.546,34.163,24.783,34.146,26.404z M0,16.962l0.05-0.286h6.028c0.813,0.031,1.468,0.29,1.694,1.159l1.311,6.304
                                C7.795,20.842,4.691,18.099,0,16.962z M17.581,16.812l-6.123,14.239l-4.114,0.007L3.862,19.161
                                c2.503,1.602,4.635,4.144,5.386,5.914l0.406,1.469l3.808-9.729L17.581,16.812L17.581,16.812z M19.153,16.8h3.89L20.61,31.066
                                h-3.888L19.153,16.8z"/>
                        </g>
                    </g>
                    </svg>
        
                </div>
                <div class="ccv">
                    <label>CVV</label>
                    <div></div>
                </div>
                </div>
            </div>
            </div>
            <form class="form" autocomplete="off" novalidate>
            <fieldset>
                <label for="card-number">Numero do Cartão</label>
                <input type="num" id="card-number" class="input-cart-number" maxlength="4" />
                <input type="num" id="card-number-1" class="input-cart-number" maxlength="4" />
                <input type="num" id="card-number-2" class="input-cart-number" maxlength="4" />
                <input type="num" id="card-number-3" class="input-cart-number" maxlength="4" />
            </fieldset>
            <fieldset>
                <label for="card-holder">Titular do Cartão</label>
                <input type="text" id="card-holder" />
            </fieldset>
            <fieldset class="fieldset-expiration">
                <label for="card-expiration-month">Data de Expiração</label>
                <div class="select">
                <select id="card-expiration-month">
                    <option></option>
                    <option>01</option>
                    <option>02</option>
                    <option>03</option>
                    <option>04</option>
                    <option>05</option>
                    <option>06</option>
                    <option>07</option>
                    <option>08</option>
                    <option>09</option>
                    <option>10</option>
                    <option>11</option>
                    <option>12</option>
                </select>
                </div>
                <div class="select">
                <select id="card-expiration-year">
                    <option></option>
                    <option>2016</option>
                    <option>2017</option>
                    <option>2018</option>
                    <option>2019</option>
                    <option>2020</option>
                    <option>2021</option>
                    <option>2022</option>
                    <option>2023</option>
                    <option>2024</option>
                    <option>2025</option>
                </select>
                </div>
            </fieldset>
            <fieldset class="fieldset-ccv">
                <label for="card-ccv">CVV</label>
                <input type="text" id="card-ccv" maxlength="3" />
            </fieldset>
            <button class="btn"><i class="fa fa-lock"></i> Pagar</button>
            </form>
        </div>
        
    </div>
    {% include "partials/_pedido.html" %}
{% endblock conteudo %}